title: Hüseyin GÜZEL
description: Bilgisayar, teknoloji, internet, elektronik 
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://huseyinguzel.web.tr" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Hüseyin GÜZEL # add your name
author-img: hello_world.jpg # add your photo
about-author: # add description

# Disqus
discus-identifier: huseyinguzel-web-tr # add your discus identifier

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed
  
kramdown:
  smart_quotes:               apos,apos,quot,quot
  typographic_symbols:        {hellip: ...}

paginate: 8
paginate_path: "/page/:num"

defaults:
  -
    scope:
      path:            "tags.html"
    values:
      sitemap:         false

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
